version: '2'
services:
  web:
    build:
      context: .
    image: ridesoft_lamp:1.0
    volumes:
      - ${PROJECT_VOLUME}/src:/var/www/html/${PROJECT_NAME}
    ports:
      - "80:80"
    domainname: ${PROJECT_NAME}.docker
    hostname: ${PROJECT_NAME}
    restart: always
    networks:
      - ridesoft

  db:
    image: mysql:5.5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ridesoft
      MYSQL_PASSWORD: ridesoft
      MYSQL_DATABASE: ridesoft
    volumes:
      - ${PROJECT_VOLUME}/data/mysql:/data
    ports:
      - 3306:3306
    networks:
      ridesoft:
        aliases:
          - mysql_db
  redis:
    image: redis
    volumes:
      - ${PROJECT_VOLUME}/data/redis:/var/lib/redis
    networks:
      ridesoft:
        aliases:
          - redis
networks:
  ridesoft:
    driver: bridge
